name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect repository
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: build
        run: |
          npm install
          npm run build
          npm run start:prod
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: db
          yaml: |-
            name: sns-api
            app: node@16
            options:
              git:
                url: https://github.com/yujiniii/sns-api.git
              docbase: /dist
      - name: start service
        run: |
          npm install